### ISSUE TITLE
Is there a way to center specific columns

### ISSUE THREAD

**Issue by bencarter78** [matfish2/vue-tables#130]
- Vue.js version: 1.0.28
- consumed using: browserify

Is there a way to center specific columns, I can't see anything obvious that would allow me to do it. Using templates maybe?

**Comment by matfish2** [comment]
How about
```css
tr td:nth-child(x) {
 text-align:center
}
```
